# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: "2025 smdn <smdn@smdn.jp>"
#
# ref: https://docs.github.com/code-security/dependabot/working-with-dependabot/dependabot-options-reference
#
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-actions-workflows:
        patterns:
          - "actions/*"
      smdn-fundamentals-workflows:
        patterns:
          - "smdn/Smdn.Fundamentals/*"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "03:18"
      timezone: "Asia/Tokyo"
    ignore:
      - dependency-name: "actions/checkout"
        update-types: ["version-update:semver-patch"]
