//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Smdn.LibHighlightSharp.Bindings {

public class highlight {
  public static readonly string GLOBAL_SR_INSTANCE_NAME = highlightPINVOKE.GLOBAL_SR_INSTANCE_NAME_get();
}

}
