//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Smdn.LibHighlightSharp.Bindings {

public enum ParseError {
  PARSE_OK,
  BAD_INPUT = 1,
  BAD_OUTPUT = 2,
  BAD_STYLE = 4,
  BAD_BINARY = 8
}

}
