//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Smdn.LibHighlightSharp.Bindings {

public enum LSResult {
  INIT_OK,
  INIT_BAD_PIPE,
  INIT_BAD_REQUEST,
  CMD_ERROR
}

}
