//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Smdn.LibHighlightSharp.Bindings {

public enum State {
  STANDARD = 0,
  STRING,
  NUMBER,
  SL_COMMENT,
  ML_COMMENT,
  ESC_CHAR,
  DIRECTIVE,
  DIRECTIVE_STRING,
  LINENUMBER,
  SYMBOL,
  STRING_INTERPOLATION,
  SYNTAX_ERROR,
  SYNTAX_ERROR_MSG,
  KEYWORD,
  STRING_END,
  NUMBER_END,
  SL_COMMENT_END,
  ML_COMMENT_END,
  ESC_CHAR_END,
  DIRECTIVE_END,
  SYMBOL_END,
  STRING_INTERPOLATION_END,
  KEYWORD_END,
  IDENTIFIER_BEGIN,
  IDENTIFIER_END,
  EMBEDDED_CODE_BEGIN,
  EMBEDDED_CODE_END,
  _UNKNOWN = 100,
  _REJECT,
  _EOL,
  _EOF,
  _WS,
  _TESTPOS
}

}
