//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Smdn.LibHighlightSharp.Bindings {

class highlightPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="SWIGRegisterExceptionCallbacks_highlight")]
    public static extern void SWIGRegisterExceptionCallbacks_highlight(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_highlight")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_highlight(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_highlight(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_highlight(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="SWIGRegisterStringCallback_highlight")]
    public static extern void SWIGRegisterStringCallback_highlight(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_highlight(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static highlightPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_DataDir_LSB_DATA_DIR_set___")]
  public static extern void DataDir_LSB_DATA_DIR_set(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_DataDir_LSB_DATA_DIR_get___")]
  public static extern string DataDir_LSB_DATA_DIR_get();

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_DataDir_LSB_CFG_DIR_set___")]
  public static extern void DataDir_LSB_CFG_DIR_set(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_DataDir_LSB_CFG_DIR_get___")]
  public static extern string DataDir_LSB_CFG_DIR_get();

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_DataDir_LSB_DOC_DIR_set___")]
  public static extern void DataDir_LSB_DOC_DIR_set(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_DataDir_LSB_DOC_DIR_get___")]
  public static extern string DataDir_LSB_DOC_DIR_get();

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_DataDir_initSearchDirectories___")]
  public static extern void DataDir_initSearchDirectories(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_DataDir_searchDataDir___")]
  public static extern void DataDir_searchDataDir(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_DataDir_printConfigPaths___")]
  public static extern void DataDir_printConfigPaths(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_DataDir_searchFile___")]
  public static extern string DataDir_searchFile(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_DataDir_getLangPath__SWIG_0___")]
  public static extern string DataDir_getLangPath__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_DataDir_getThemePath__SWIG_0___")]
  public static extern string DataDir_getThemePath__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_DataDir_getLangPath__SWIG_1___")]
  public static extern string DataDir_getLangPath__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_DataDir_getSystemDataPath___")]
  public static extern string DataDir_getSystemDataPath(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_DataDir_getThemePath__SWIG_1___")]
  public static extern string DataDir_getThemePath__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_DataDir_getThemePath__SWIG_2___")]
  public static extern string DataDir_getThemePath__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_DataDir_getFiletypesConfPath___")]
  public static extern string DataDir_getFiletypesConfPath(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_DataDir_getPluginPath__SWIG_0___")]
  public static extern string DataDir_getPluginPath__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_DataDir_getPluginPath__SWIG_1___")]
  public static extern string DataDir_getPluginPath__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_DataDir_getI18nDir___")]
  public static extern string DataDir_getI18nDir(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_DataDir_getExtDir___")]
  public static extern string DataDir_getExtDir(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_DataDir_getDocDir___")]
  public static extern string DataDir_getDocDir(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_new_DataDir___")]
  public static extern global::System.IntPtr new_DataDir();

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_delete_DataDir___")]
  public static extern void delete_DataDir(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_GLOBAL_SR_INSTANCE_NAME_get___")]
  public static extern string GLOBAL_SR_INSTANCE_NAME_get();

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_new_SyntaxReader___")]
  public static extern global::System.IntPtr new_SyntaxReader();

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_delete_SyntaxReader___")]
  public static extern void delete_SyntaxReader(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_load___")]
  public static extern int SyntaxReader_load(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_needsReload___")]
  public static extern bool SyntaxReader_needsReload(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_getFailedRegex___")]
  public static extern string SyntaxReader_getFailedRegex(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_getLuaErrorText___")]
  public static extern string SyntaxReader_getLuaErrorText(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_getRawStringPrefix___")]
  public static extern byte SyntaxReader_getRawStringPrefix(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_getContinuationChar___")]
  public static extern byte SyntaxReader_getContinuationChar(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_highlightingEnabled___")]
  public static extern bool SyntaxReader_highlightingEnabled(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_isIgnoreCase___")]
  public static extern bool SyntaxReader_isIgnoreCase(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_isKeyword___")]
  public static extern int SyntaxReader_isKeyword(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_allowNestedMLComments___")]
  public static extern bool SyntaxReader_allowNestedMLComments(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_highlightingDisabled___")]
  public static extern bool SyntaxReader_highlightingDisabled(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_enableReformatting___")]
  public static extern bool SyntaxReader_enableReformatting(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_assertDelimEqualLength___")]
  public static extern bool SyntaxReader_assertDelimEqualLength(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_getKeywords___")]
  public static extern global::System.IntPtr SyntaxReader_getKeywords(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_getKeywordClasses___")]
  public static extern global::System.IntPtr SyntaxReader_getKeywordClasses(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_getRegexElements___")]
  public static extern global::System.IntPtr SyntaxReader_getRegexElements(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_getDescription___")]
  public static extern string SyntaxReader_getDescription(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_getHeaderInjection___")]
  public static extern string SyntaxReader_getHeaderInjection(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_getFooterInjection___")]
  public static extern string SyntaxReader_getFooterInjection(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_delimiterIsDistinct___")]
  public static extern bool SyntaxReader_delimiterIsDistinct(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_delimiterIsRawString___")]
  public static extern bool SyntaxReader_delimiterIsRawString(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_getOpenDelimiterID___")]
  public static extern int SyntaxReader_getOpenDelimiterID(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_matchesOpenDelimiter___")]
  public static extern bool SyntaxReader_matchesOpenDelimiter(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, int jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_restoreLangEndDelim___")]
  public static extern void SyntaxReader_restoreLangEndDelim(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_allowsInnerSection___")]
  public static extern bool SyntaxReader_allowsInnerSection(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_getNewPath___")]
  public static extern string SyntaxReader_getNewPath(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_getCurrentPath___")]
  public static extern string SyntaxReader_getCurrentPath(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_getOverrideConfigVal___")]
  public static extern string SyntaxReader_getOverrideConfigVal(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_getValidateStateChangeFct___")]
  public static extern global::System.IntPtr SyntaxReader_getValidateStateChangeFct(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_getDecorateFct___")]
  public static extern global::System.IntPtr SyntaxReader_getDecorateFct(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_getDecorateLineBeginFct___")]
  public static extern global::System.IntPtr SyntaxReader_getDecorateLineBeginFct(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_getDecorateLineEndFct___")]
  public static extern global::System.IntPtr SyntaxReader_getDecorateLineEndFct(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_getLuaState___")]
  public static extern global::System.IntPtr SyntaxReader_getLuaState(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_addUserChunk___")]
  public static extern void SyntaxReader_addUserChunk(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_initLuaState__SWIG_0___")]
  public static extern void SyntaxReader_initLuaState__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_SyntaxReader_initLuaState__SWIG_1___")]
  public static extern void SyntaxReader_initLuaState__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_new_RegexElement__SWIG_0___")]
  public static extern global::System.IntPtr new_RegexElement__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_new_RegexElement__SWIG_1___")]
  public static extern global::System.IntPtr new_RegexElement__SWIG_1(int jarg1, int jarg2, string jarg3, uint jarg4, int jarg5, string jarg6);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_new_RegexElement__SWIG_2___")]
  public static extern global::System.IntPtr new_RegexElement__SWIG_2(int jarg1, int jarg2, string jarg3, uint jarg4, int jarg5);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_new_RegexElement__SWIG_3___")]
  public static extern global::System.IntPtr new_RegexElement__SWIG_3(int jarg1, int jarg2, string jarg3, uint jarg4);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_new_RegexElement__SWIG_4___")]
  public static extern global::System.IntPtr new_RegexElement__SWIG_4(int jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_delete_RegexElement___")]
  public static extern void delete_RegexElement(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_RegexElement_open_set___")]
  public static extern void RegexElement_open_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_RegexElement_open_get___")]
  public static extern int RegexElement_open_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_RegexElement_end_set___")]
  public static extern void RegexElement_end_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_RegexElement_end_get___")]
  public static extern int RegexElement_end_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_RegexElement_rex_set___")]
  public static extern void RegexElement_rex_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_RegexElement_rex_get___")]
  public static extern global::System.IntPtr RegexElement_rex_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_RegexElement_kwClass_set___")]
  public static extern void RegexElement_kwClass_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_RegexElement_kwClass_get___")]
  public static extern uint RegexElement_kwClass_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_RegexElement_capturingGroup_set___")]
  public static extern void RegexElement_capturingGroup_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_RegexElement_capturingGroup_get___")]
  public static extern int RegexElement_capturingGroup_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_RegexElement_langName_set___")]
  public static extern void RegexElement_langName_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_RegexElement_langName_get___")]
  public static extern string RegexElement_langName_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_RegexElement_instanceCnt_set___")]
  public static extern void RegexElement_instanceCnt_set(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_RegexElement_instanceCnt_get___")]
  public static extern int RegexElement_instanceCnt_get();

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_RegexElement_instanceId_set___")]
  public static extern void RegexElement_instanceId_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_RegexElement_instanceId_get___")]
  public static extern int RegexElement_instanceId_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_new_RegexDef___")]
  public static extern global::System.IntPtr new_RegexDef();

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_RegexDef_reString_set___")]
  public static extern void RegexDef_reString_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_RegexDef_reString_get___")]
  public static extern string RegexDef_reString_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_RegexDef_capturingGroup_set___")]
  public static extern void RegexDef_capturingGroup_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_RegexDef_capturingGroup_get___")]
  public static extern int RegexDef_capturingGroup_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_delete_RegexDef___")]
  public static extern void delete_RegexDef(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_new_ReGroup__SWIG_0___")]
  public static extern global::System.IntPtr new_ReGroup__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_new_ReGroup__SWIG_1___")]
  public static extern global::System.IntPtr new_ReGroup__SWIG_1(int jarg1, uint jarg2, uint jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_new_ReGroup__SWIG_2___")]
  public static extern global::System.IntPtr new_ReGroup__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_delete_ReGroup___")]
  public static extern void delete_ReGroup(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_ReGroup_length_set___")]
  public static extern void ReGroup_length_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_ReGroup_length_get___")]
  public static extern uint ReGroup_length_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_ReGroup_state_set___")]
  public static extern void ReGroup_state_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_ReGroup_state_get___")]
  public static extern int ReGroup_state_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_ReGroup_kwClass_set___")]
  public static extern void ReGroup_kwClass_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_ReGroup_kwClass_get___")]
  public static extern uint ReGroup_kwClass_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_ReGroup_name_set___")]
  public static extern void ReGroup_name_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_ReGroup_name_get___")]
  public static extern string ReGroup_name_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_delete_CodeGenerator___")]
  public static extern void delete_CodeGenerator(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_getInstance___")]
  public static extern global::System.IntPtr CodeGenerator_getInstance(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_deleteInstance___")]
  public static extern void CodeGenerator_deleteInstance(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_initTheme___")]
  public static extern bool CodeGenerator_initTheme(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_getThemeInitError___")]
  public static extern string CodeGenerator_getThemeInitError(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_getPluginScriptError___")]
  public static extern string CodeGenerator_getPluginScriptError(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_initIndentationScheme___")]
  public static extern bool CodeGenerator_initIndentationScheme(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setIndentationOptions___")]
  public static extern void CodeGenerator_setIndentationOptions(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_loadLanguage__SWIG_0___")]
  public static extern int CodeGenerator_loadLanguage__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_loadLanguage__SWIG_1___")]
  public static extern int CodeGenerator_loadLanguage__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_generateFile___")]
  public static extern int CodeGenerator_generateFile(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_generateString___")]
  public static extern string CodeGenerator_generateString(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_generateStringFromFile___")]
  public static extern string CodeGenerator_generateStringFromFile(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_printExternalStyle___")]
  public static extern bool CodeGenerator_printExternalStyle(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_printIndexFile___")]
  public static extern bool CodeGenerator_printIndexFile(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setPreformatting___")]
  public static extern void CodeGenerator_setPreformatting(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, uint jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_styleFound___")]
  public static extern bool CodeGenerator_styleFound(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_formattingDisabled___")]
  public static extern bool CodeGenerator_formattingDisabled(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_formattingIsPossible___")]
  public static extern bool CodeGenerator_formattingIsPossible(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setPrintLineNumbers__SWIG_0___")]
  public static extern void CodeGenerator_setPrintLineNumbers__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setPrintLineNumbers__SWIG_1___")]
  public static extern void CodeGenerator_setPrintLineNumbers__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_getPrintLineNumbers___")]
  public static extern bool CodeGenerator_getPrintLineNumbers(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setPrintZeroes___")]
  public static extern void CodeGenerator_setPrintZeroes(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_getPrintZeroes___")]
  public static extern bool CodeGenerator_getPrintZeroes(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setFragmentCode___")]
  public static extern void CodeGenerator_setFragmentCode(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_getFragmentCode___")]
  public static extern bool CodeGenerator_getFragmentCode(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setLineNumberWidth___")]
  public static extern void CodeGenerator_setLineNumberWidth(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_getLineNumberWidth___")]
  public static extern int CodeGenerator_getLineNumberWidth(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setValidateInput___")]
  public static extern void CodeGenerator_setValidateInput(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_getValidateInput___")]
  public static extern bool CodeGenerator_getValidateInput(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setKeepInjections___")]
  public static extern void CodeGenerator_setKeepInjections(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_getKeepInjections___")]
  public static extern bool CodeGenerator_getKeepInjections(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setNumberWrappedLines___")]
  public static extern void CodeGenerator_setNumberWrappedLines(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_getNumberWrappedLines___")]
  public static extern bool CodeGenerator_getNumberWrappedLines(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setOmitVersionComment___")]
  public static extern void CodeGenerator_setOmitVersionComment(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_getOmitVersionComment___")]
  public static extern bool CodeGenerator_getOmitVersionComment(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_getStyleName___")]
  public static extern string CodeGenerator_getStyleName(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setBaseFont___")]
  public static extern void CodeGenerator_setBaseFont(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_getBaseFont___")]
  public static extern string CodeGenerator_getBaseFont(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setBaseFontSize___")]
  public static extern void CodeGenerator_setBaseFontSize(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_getBaseFontSize___")]
  public static extern string CodeGenerator_getBaseFontSize(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setIncludeStyle___")]
  public static extern void CodeGenerator_setIncludeStyle(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_disableTrailingNL___")]
  public static extern void CodeGenerator_disableTrailingNL(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setStyleInputPath___")]
  public static extern void CodeGenerator_setStyleInputPath(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setStyleOutputPath___")]
  public static extern void CodeGenerator_setStyleOutputPath(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setEncoding___")]
  public static extern void CodeGenerator_setEncoding(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_getStyleInputPath___")]
  public static extern string CodeGenerator_getStyleInputPath(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_getStyleOutputPath___")]
  public static extern string CodeGenerator_getStyleOutputPath(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setTitle___")]
  public static extern void CodeGenerator_setTitle(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_getTitle___")]
  public static extern string CodeGenerator_getTitle(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setStartingInputLine___")]
  public static extern void CodeGenerator_setStartingInputLine(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setMaxInputLineCnt___")]
  public static extern void CodeGenerator_setMaxInputLineCnt(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setKeyWordCase___")]
  public static extern void CodeGenerator_setKeyWordCase(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setEOLDelimiter___")]
  public static extern void CodeGenerator_setEOLDelimiter(global::System.Runtime.InteropServices.HandleRef jarg1, char jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setStartingNestedLang___")]
  public static extern void CodeGenerator_setStartingNestedLang(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setPluginParameter___")]
  public static extern void CodeGenerator_setPluginParameter(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_initPluginScript___")]
  public static extern bool CodeGenerator_initPluginScript(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_getSyntaxRegexError___")]
  public static extern string CodeGenerator_getSyntaxRegexError(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_getSyntaxLuaError___")]
  public static extern string CodeGenerator_getSyntaxLuaError(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_getSyntaxDescription___")]
  public static extern string CodeGenerator_getSyntaxDescription(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_getThemeDescription___")]
  public static extern string CodeGenerator_getThemeDescription(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_getSyntaxReader___")]
  public static extern global::System.IntPtr CodeGenerator_getSyntaxReader(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setHTMLAttachAnchors___")]
  public static extern void CodeGenerator_setHTMLAttachAnchors(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setHTMLOrderedList___")]
  public static extern void CodeGenerator_setHTMLOrderedList(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setHTMLInlineCSS___")]
  public static extern void CodeGenerator_setHTMLInlineCSS(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setHTMLEnclosePreTag___")]
  public static extern void CodeGenerator_setHTMLEnclosePreTag(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setHTMLUseNonBreakingSpace___")]
  public static extern void CodeGenerator_setHTMLUseNonBreakingSpace(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setHTMLAnchorPrefix___")]
  public static extern void CodeGenerator_setHTMLAnchorPrefix(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setHTMLClassName___")]
  public static extern void CodeGenerator_setHTMLClassName(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setLATEXReplaceQuotes___")]
  public static extern void CodeGenerator_setLATEXReplaceQuotes(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setLATEXNoShorthands___")]
  public static extern void CodeGenerator_setLATEXNoShorthands(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setLATEXPrettySymbols___")]
  public static extern void CodeGenerator_setLATEXPrettySymbols(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setLATEXBeamerMode___")]
  public static extern void CodeGenerator_setLATEXBeamerMode(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setRTFPageSize___")]
  public static extern void CodeGenerator_setRTFPageSize(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setRTFCharStyles___")]
  public static extern void CodeGenerator_setRTFCharStyles(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setRTFPageColor___")]
  public static extern void CodeGenerator_setRTFPageColor(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setSVGSize___")]
  public static extern void CodeGenerator_setSVGSize(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setESCTrueColor___")]
  public static extern void CodeGenerator_setESCTrueColor(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("highlight-v3_44_0_0", EntryPoint="CSharp_SmdnfLibHighlightSharpfBindings_CodeGenerator_setESCCanvasPadding___")]
  public static extern void CodeGenerator_setESCCanvasPadding(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);
}

}
