//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Smdn.LibHighlightSharp.Bindings {

public class ReGroup : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ReGroup(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ReGroup obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ReGroup() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          highlightPINVOKE.delete_ReGroup(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ReGroup() : this(highlightPINVOKE.new_ReGroup__SWIG_0(), true) {
  }

  public ReGroup(State s, uint l, uint c, string n) : this(highlightPINVOKE.new_ReGroup__SWIG_1((int)s, l, c, n), true) {
    if (highlightPINVOKE.SWIGPendingException.Pending) throw highlightPINVOKE.SWIGPendingException.Retrieve();
  }

  public ReGroup(ReGroup other) : this(highlightPINVOKE.new_ReGroup__SWIG_2(ReGroup.getCPtr(other)), true) {
    if (highlightPINVOKE.SWIGPendingException.Pending) throw highlightPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint length {
    set {
      highlightPINVOKE.ReGroup_length_set(swigCPtr, value);
    } 
    get {
      uint ret = highlightPINVOKE.ReGroup_length_get(swigCPtr);
      return ret;
    } 
  }

  public State state {
    set {
      highlightPINVOKE.ReGroup_state_set(swigCPtr, (int)value);
    } 
    get {
      State ret = (State)highlightPINVOKE.ReGroup_state_get(swigCPtr);
      return ret;
    } 
  }

  public uint kwClass {
    set {
      highlightPINVOKE.ReGroup_kwClass_set(swigCPtr, value);
    } 
    get {
      uint ret = highlightPINVOKE.ReGroup_kwClass_get(swigCPtr);
      return ret;
    } 
  }

  public string name {
    set {
      highlightPINVOKE.ReGroup_name_set(swigCPtr, value);
      if (highlightPINVOKE.SWIGPendingException.Pending) throw highlightPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = highlightPINVOKE.ReGroup_name_get(swigCPtr);
      if (highlightPINVOKE.SWIGPendingException.Pending) throw highlightPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

}

}
