# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: "2022 smdn <smdn@smdn.jp>"

name: Publish release target manual dispatcher

on:
  workflow_dispatch:
    inputs:
      pr_number_request_for_release:
        description: "The number of pull request that requests to merge the release working branch."
        required: true
        type: string

jobs:
  run-publish-release-target:
    uses: smdn/Smdn.Fundamentals/.github/workflows/publish-release-target.yml@workflows/release-target-v1.5.5
    with:
      pr_number_request_for_release: ${{ fromJson(github.event.inputs.pr_number_request_for_release) }}
      pr_label_request_for_release:  'release-target'
    secrets:
      token_repo:                 ${{ secrets.PUBLISH_NEW_RELEASE }}
      token_push_nuget_org:       ${{ secrets.PUBLISH_PACKAGE_NUGETORG }}
      token_push_github_packages: ${{ secrets.PUBLISH_NEW_RELEASE }}
